{% set name = "enlopy" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df23ead4b235ba6b48462bd1d7aa8578cc2859e2f2db4f442f6adf859c779574

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=3.3
  run:
    - matplotlib-base >=2.2
    - numpy >=1.10
    - pandas >=1.4
    - python >=3.9
    - scipy >=1.10

test:
  imports:
    - enlopy

about:
  home: https://github.com/kavvkon/enlopy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library with methods to generate, process, analyze, and plot energy related timeseries.
  doc_url: https://enlopy.readthedocs.io/
  dev_url: https://www.github.com/kavvkon/enlopy

extra:
  recipe-maintainers:
    - kavvkon
