{% set name = "enlopy" %}
{% set version = "0.1.dev12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0b6b7b2fe99208bd5be31e0f90baadf1eff2a3f9c152d99bed6a3bb040257a3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools >=3.3
  run:
    - matplotlib >=2.5
    - numpy >=1.12
    - pandas >=0.20
    - python
    - scipy >=1.0

test:
  imports:
    - enlopy

about:
  home: https://github.com/kavvkon/enlopy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE 
  summary: Python library with methods to generate, process, analyze, and plot energy related timeseries.
  doc_url: https://enlopy.readthedocs.io/
  dev_url: https://www.github.com/kavvkon/enlopy

extra:
  recipe-maintainers:
    - kavvkon
