travis:
  secure:
    BINSTAR_TOKEN: oQI/n9hrxLftkFtbHkXDZMrKrS4bT0bUdyy/cJfKtlZf+ZPLzMEeKdFh9mD0aAOaMaO9WTDrzDl0jja0mQ9fKONAEazaug4BoZSj9hqTVq8VMKLNOvcP6MB7ogg0nSetD++wJ+fmHJ1LTXhP5YUlgVgtIpnF37sDY9BftOb7uaUouitdFnzVIPSYryOPeMGOrR3IcWcez4N2EN+CWRbAkJ4mXpY7IqVgEe9/6qH9B3i3OZ31vmLHZTrnG8XBmPlYTcgbXsaY1fT9AiyTr40H/twicMbBCQxWj3lnSy66CEGqpApQbD9Uo5drR3FliqyogzvueoSIV50W47a9J52Eg90C7+KX2dWKrEuvWNeExNm45lOoNzuwI4HTpKYOXhPVXgJeUuVeknnR26Mp/VZb2ndw5MiLDMlUsHEGmkT+Xhzv8x5mKsexKrDF1GltNmb78k/Qffc7pLcUcw2ZRktprLCfSVjTLFV5N6SRosQVu2V0urF87GoaiVmPAKU4gLNjs8Bl2GNFcdU9I73SGWEBXJLbuTLPQF9+BDTES+fipowcxp93zubuaT98LYhhdHn1LPgF77IlIJhL5ZIcquWCpKjkny2E6fHb6lmEMFLQ1eo8hjJkdrvn0sWtQqvmeMDZxgq2Y86YttxZjb4/pgzyHWJa0rAw178re8ZpjQZldPM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
